### ISSUE TITLE
请问大佬py文件怎么用

### ISSUE THREAD

**Issue by Adkimsm** [typlog/yue.css#17]
大佬，`template.py` 根据代码判断是用于生成html，但我发现运行后无法生成，无任何报错，代码也无任何修改，py环境 ` 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] on win32`

**Comment by Adkinsm2020** [comment]
模块也已安装
